---
- block:

  - name: Update timezone
    timezone:
      name: US/Central
  
  - name: Ensure filesystem for Consul
    filesystem:
      dev: "{{ consul_disk_device }}"
      fstype: ext4

  - name: Mount consul filesystem
    mount:
      name: "{{ consul_mountpoint }}"
      src: "{{ consul_disk_device }}"
      fstype: ext4
      state: mounted

  - name: Unpack Consul
    unarchive:
      copy: no
      src: "{{ consul_url }}"
      dest: /usr/local/bin
      creates: /usr/local/bin/consul

  - name: Ensure Consul group exists
    group:
      name: consul

  - name: Ensure Consul user exists
    user:
      name: consul
      group: consul
      system: yes

  - name: Ensure Consul is executable
    file:
      path: /usr/local/bin/consul
      mode: 0755
      owner: root
      group: root

  - name: Ensure Consul configuration directory exists
    file:
      path: /etc/consul.d
      mode: 0755
      owner: consul
      group: consul
      state: directory

  - name: Ensure Consul data directory exists
    file:
      path: "{{ consul_mountpoint }}"
      mode: 0755
      owner: consul
      group: consul
      state: directory

  - name: Copy consul upstart script
    copy:
      src: consul.conf
      dest: /etc/init/consul.conf
      owner: root
      group: root
      mode: 0644

  - name: Add Consul log file
    file:
      path: /var/log/consul.log
      mode: 0744
      owner: consul
      group: consul
      state: touch

  - name: Add Consul logrotate file
    copy:
      src: consul.logrotate
      dest: /etc/logrotate.d/consul
      owner: root
      group: root

  - name: Copy default consul configuration
    copy:
      src: client.json
      dest: /etc/consul.d/client.json
      mode: 0644
      owner: consul
      group: consul

  - name: Disable consul service
    service:
      name: consul
      enabled: no

  become: yes
