---
- block:

  - name: Copy consul upstart script
    copy:
      src: consul.conf
      dest: /etc/init/consul.conf
      owner: root
      group: root
      mode: 0644

  - name: Copy consul server configuration
    copy:
      src: server.json
      dest: /etc/consul.d/server.json
      owner: consul
      group: consul
      mode: 0644

  - name: Enable consul service
    service:
      name: consul
      enabled: yes

  become: yes
