---
- block:

  - name: Copy consul server configuration
    copy:
      src: server.json
      dest: /etc/consul.d/server.json
      owner: consul
      group: consul
      mode: 0644

  - name: Remove client configuration
    file:
      path: /etc/consul.d/client.json
      state: absent

  - name: Enable consul service
    service:
      name: consul
      enabled: yes

  become: yes
